application/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy # type: ignore
from flask_login import LoginManager  # type: ignore
from config import *
from flask_mail import Mail   # type: ignore
#from flask_socketio import SocketIO, emit

db = SQLAlchemy()
#socketio = SocketIO()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = "auth.newlogin"


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    UPLOAD_PATH = 'static/css/images/profiles/'
    UPLOAD_PRODUCTS = 'static/css/images/products/'
    UPLOAD_PAYMENT_PROOF = 'static/css/images/payments/'
    login_manager.init_app(app)
    app.config['UPLOAD_PATH'] = UPLOAD_PATH
    app.config['UPLOAD_PRODUCTS'] = UPLOAD_PRODUCTS
    app.config['UPLOAD_PAYMENT_PROOF'] = UPLOAD_PAYMENT_PROOF

    db.init_app(app)

    mail = Mail(app)
    mail.init_app(app)

    #routes will go here
    #blueprint registration

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    from .admin import   admin as admin_blueprint
    app.register_blueprint(admin_blueprint, url_prefix='/admin')

    from .pharmacy import pharmacy as pharmscy_blueprint
    app.register_blueprint(pharmscy_blueprint, url_prefix='/pharmacy')
    
    from .delivery import delivery as delivery_blueprint
    app.register_blueprint(delivery_blueprint, url_prefix='/delivery')
#
  #      from application.models import Pharmacy # type: ignore
   #     pharmacies = Pharmacy.query.all()
    #    return dict(pharmacies=pharmacies)

    return app

application/admin/__init__.py
from flask import Blueprint

admin = Blueprint('admin', __name__)

from . import views

application/admin/views.py
from flask import render_template, redirect, url_for, request, flash, current_app, jsonify,session
from sqlalchemy.exc import IntegrityError
from sqlalchemy import func, extract, or_
from ..models import *
from datetime import datetime,timedelta
import calendar
from flask_login import login_required, current_user, logout_user,  LoginManager # type: ignore
from . import admin
from ..forms import *
from ..models import db
import os
from application.auth import *
import secrets
from PIL import Image
from flask import current_app
import plotly.graph_objs as go # type: ignore
import plotly.offline as plot # type: ignore



def save_product_picture(file):
    # Set the desired size for resizing
    size = (300, 300)

    # Generate a random hex string for the filename
    random_hex = secrets.token_hex(9)

    # Get the file extension
    _, f_ex = os.path.splitext(file.filename)


    # Generate the final filename (random + extension)
    post_img_fn = random_hex + f_ex

    # Define the path to save the file (UPLOAD_PRODUCTS should be configured in your Flask app)
    post_image_path = os.path.join(current_app.root_path, current_app.config['UPLOAD_PRODUCTS'], post_img_fn)

    try:
        # Open the image
        img = Image.open(file)

        # Resize the image to fit within the size (thumbnail)
        img.thumbnail(size)

        # Save the resized image
        img.save(post_image_path)

        return post_img_fn  # Return the filename to store in the database
    except Exception as e:
        # If an error occurs during image processing, handle it
        print(f"Error saving image: {e}")
        return None

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.newlogin'

@login_manager.user_loader
def load_user(user_id):
    user_type = session.get('user_type')
    if user_type == 'pharmacy':
        if Pharmacy.query.get(int(user_id)):
            return Pharmacy.query.get(int(user_id))
        else:
            return Staff.query.get(int(user_id))
    elif user_type == 'customer':
        return User.query.get(int(user_id))
    elif user_type == 'delivery_guy':
        return DeliveryGuy.query.get(int(user_id))

    return None


@admin.route('/admindash', methods=["GET", "POST"])
def admindash():
    pending_pharmacy = Pharmacy.query.filter(Pharmacy.verified == False).all()
    count = len(pending_pharmacy)
    today = datetime.today()
    current_month, current_year = today.month, today.year
    start_of_month = today.replace(day=1, hour=0, minute=0, second=0, microsecond=0)
    next_month = (today.replace(day=28) + timedelta(days=4)).replace(day=1)
    end_of_month = next_month - timedelta(seconds=1)
    start_of_year = today.replace(month=1, day=1, hour=0, minute=0, second=0, microsecond=0)
    end_of_year = today.replace(month=12, day=31, hour=23, minute=59, second=59, microsecond=999999)

    total_sales = db.session.query(func.sum((Sales.price*0.18)*Sales.quantity)).scalar() or 0.0

    daily_sales = db.session.query(
            func.date(Sales.date_).label('date'),
            func.sum(((Sales.price *0.18)* Sales.quantity)).label('total')
        ).group_by(func.date(Sales.date_)).order_by(
            func.date(Sales.date_)).all() or 0.0
    total_monthly_sales = db.session.query(func.sum((Sales.price *0.18) * Sales.quantity)).filter(
            Sales.date_ >= start_of_month, Sales.date_ <= end_of_month).scalar() or 0.0

    total_annual_sales = db.session.query(func.sum((Sales.price *0.18)* Sales.quantity)).filter(
            Sales.date_ >= start_of_year, Sales.date_ <= end_of_year).scalar() or 0.0

    today_sales = db.session.query(func.sum((Sales.price *0.18)* Sales.quantity)).filter(
            func.date(Sales.date_) == today.date()).scalar() or 0.0    

    return render_template('admin/admindash.html', count=count, daily_sales=daily_sales,
                           total_annual_sales=total_annual_sales, total_monthly_sales=total_monthly_sales,
                           today_sales=today_sales, total_sales=total_sales)

@admin.route('/verify pharmacy/<int:pharmacy_id>', methods=["GET", "POST"])
def verifypharmacy(pharmacy_id):
    pharmacy = Pharmacy.query.get_or_404(pharmacy_id)
    if pharmacy:
        pharmacy.verified = True
        db.session.add(pharmacy)
    try:
        db.session.commit()
        flash('Pharmacy Verified.')
        return redirect(url_for('admin.pending_verification'))
    except IntegrityError:
        flash('Pharmacies failed due to integrity.')
        return redirect(url_for('admin.pending_verification'))

@admin.route('/cancelled pharmacy/<int:pharmacy_id>')
def cancel_pharmacy(pharmacy_id):
    pharmacy = Pharmacy.query.get_or_404(pharmacy_id)
    if pharmacy:
        db.session.delete(pharmacy)
        db.session.commit()
        return redirect(url_for('admin.pending_verification'))
    else:
        flash('Pharmacy could not be found')
        return redirect(url_for('admin.pending_verification'))

@admin.route('/registered pharmacies')
def registered_pharmacies():
    pharmacies = Pharmacy.query.filter(Pharmacy.verified == True, Pharmacy.confirmed == True).all()
    return render_template('admin/registereduser.html', pharmacies=pharmacies)

@admin.route('/register_pharmacy')
def register_pharmacy():
    form = PharmacyRegistrationForm()
    return render_template('auth/registerphar.html', form=form)

@admin.route('/pending vefication')
def pending_verification():
    pharmacies = Pharmacy.query.filter(Pharmacy.verified == False).all()
    return render_template('admin/pendingpharmacies.html', pharmacies=pharmacies)

application/delivery/__init__.py
from flask import Blueprint

delivery = Blueprint('delivery', __name__)

from . import views, errors

application/delivery/views.py
import os
from datetime import datetime, timedelta
from PIL import Image
from flask import render_template, redirect, url_for, flash, session
from flask_login import login_required, current_user, logout_user  # type: ignore
from sqlalchemy import desc, func
from sqlalchemy.exc import IntegrityError

from application.utils.notification import create_notification
from . import delivery
from ..forms import *
from ..models import *


@login_manager.user_loader
def load_user(user_id):
    user_type = session.get('user_type')
    if user_type == 'pharmacy':
        if Pharmacy.query.get(int(user_id)):
            return Pharmacy.query.get(int(user_id))
        else:
            return Staff.query.get(int(user_id))
    elif user_type == 'customer':
        return User.query.get(int(user_id))
    elif user_type == 'delivery_guy':
        return DeliveryGuy.query.get(int(user_id))

    return None

def save_delivery_picture(file):
    # Set the desired size for resizing
    size = (300, 300)

    # Generate a random hex string for the filename
    random_hex = secrets.token_hex(9)

    # Get the file extension
    _, f_ex = os.path.splitext(file.filename)

    # Generate the final filename (random + extension)
    post_img_fn = random_hex + f_ex

    # Define the path to save the file (UPLOAD_PRODUCTS should be configured in your Flask app)
    post_image_path = os.path.join(current_app.root_path, current_app.config['UPLOAD_DELIVERY'], post_img_fn)

    try:
        # Open the image
        img = Image.open(file)

        # Resize the image to fit within the size (thumbnail)
        img.thumbnail(size)

        # Save the resized image
        img.save(post_image_path)

        return post_img_fn  # Return the filename to store in the database
    except Exception as e:
        # If an error occurs during image processing, handle it
        print(f"Error saving image: {e}")
        return None


@delivery.route('/dashboard', methods=["GET", "POST"])
@login_required
def dashboard():
    pharmacy = Pharmacy.query.get(session.get('pharmacy_id'))
    formpharm = Set_PharmacyForm()
    formpharm.pharmacy.choices=[(-1, "Select a Pharmacy")] + [(p.id, p.name) for p in Pharmacy.query.all()]
    deliveries = Delivery.query.filter_by(delivery_guy_id=current_user.id).all()
    total = len(deliveries)
    delivered = [d for d in deliveries if d.status == 'Delivered']
    revenue=len(delivered) * 10
    cancelled = [d for d in deliveries if d.status == 'Cancelled']
    in_progress = [d for d in deliveries if d.status not in ['Delivered', 'Cancelled']]

    success_rate = (len(delivered) / total * 100) if total !=0 else 0
    today = datetime.utcnow()
    start_of_day = today.replace(hour=0, minute=0, second=0, microsecond=0)
    end_of_day = start_of_day + timedelta(days=1)
    # Daily Statistics
    deliveries_today = db.session.query(Delivery).filter(
        Delivery.end_time >= start_of_day,
        Delivery.end_time < end_of_day,
        Delivery.status == "Delivered"
    ).all()
    daily_revenue = len(deliveries_today)*10
    print(daily_revenue)

    start_of_week = start_of_day - timedelta(days=start_of_day.weekday())
    end_of_week = start_of_week + timedelta(weeks=1)

    weekly_count = db.session.query(Delivery).filter(
        Delivery.end_time >= start_of_week,
        Delivery.end_time < end_of_week,
        Delivery.status == "Delivered"
    ).all()

    weekly_revenue = len(weekly_count)*10
    print(weekly_revenue)


    return render_template('delivery/deliverystats.html',
                           total=total,

                           weekly_revenue=weekly_revenue,
                           daily_revenue=daily_revenue,
                           delivered=len(delivered),
                           in_progress=len(in_progress),
                           cancelled=len(cancelled),
                           pharmacy=pharmacy,
                           revenue=revenue,
                           formpharm=formpharm,
                           success_rate=round(success_rate, 2),
                          )
@delivery.route('/takeorder/<int:order_id>', methods=["GET", "POST"])
@login_required
def takeorder(order_id):
    order = Order.query.filter(Order.id==order_id, Order.pharmacy_id==session.get('pharmacy_id')).first()
    existing_deliveries_count = db.session.query(Delivery).join(Order).filter(Delivery.delivery_guy_id == current_user.id, Order.status == "Out for Delivery").count()
    if existing_deliveries_count >= 5:
        flash('You cannot take more than 5 orders at a time.')
        return redirect(url_for('delivery.dashboard'))
    user = User.query.get_or_404(order.user_id)
    cust_names=user.firstname + " " + user.lastname
    new_delivery = Delivery(customer_name = cust_names,
        address=order.location,
        delivery_guy_id=current_user.id,
        order_id=order.order_id,
        status="Out for Delivery")
    order.status = "Out for Delivery"
    order.deliveryguy = current_user.names
    order.taken_by = current_user.id
    db.session.add(order)
    db.session.add(new_delivery)
    try:
        db.session.commit()
        flash('Order taken successfully.')
    except IntegrityError:
        db.session.rollback()
        flash('An integrity error occurred.')
        return redirect(url_for('delivery.dashboard'))

    return redirect(url_for('delivery.dashboard'))


from flask import jsonify

@delivery.route('/api/delivery/<order_id>', methods=['GET'])
@login_required
def get_delivery_status(order_id):
    delivery = Delivery.query.filter_by(order_id=order_id).first()
    if delivery:
        return jsonify(delivery.to_dict())
    return jsonify({"error": "Delivery not found"}), 404



@delivery.route('/mydeliveries', methods=["POST", "GET"])
@login_required
def mydeliveries():
    pharmacy = Pharmacy.query.get_or_404(session.get('pharmacy_id'))
    myform = updatedeliveryform()
    delivery_update = updatedeliveryform()
    deliveries = Delivery.query.filter(
        Delivery.delivery_guy_id == current_user.id,
        Delivery.status == "Out for Delivery"
    ).all()
    formpharm=Set_PharmacyForm()
    formpharm.pharmacy.choices=[(-1, "Select a Pharmacy")] + [(p.id, p.name) for p in Pharmacy.query.all()]
  
    return render_template('delivery/ActiveOrder.html', myform=myform, pharmacy=pharmacy,
                           deliveries=deliveries, delivery_update=delivery_update,formpharm=formpharm)

@delivery.route('/ready orders')
@login_required
def ready_orders():
    pharmacy = Pharmacy.query.get_or_404(session.get('pharmacy_id'))
    myform = updatedeliveryform()
    delivery_update = updatedeliveryform()
    formpharm=Set_PharmacyForm()
    formpharm.pharmacy.choices=[(-1, "Select a Pharmacy")] + [(p.id, p.name) for p in Pharmacy.query.all()]
    ready = Order.query.filter(Order.status == "Ready ", Order.pharmacy_id == session.get('pharmacy_id')).all()
    return render_template('delivery/deliverydashboard.html', ready_orders=ready, myform=myform, pharmacy=pharmacy,
                           delivery_update=delivery_update,formpharm=formpharm)


@delivery.route('/update_delivery/<int:delivery_id>', methods=["GET", "POST"])
@login_required
def update_delivery(delivery_id):
    form = updatedeliveryform()
    delivery = Delivery.query.get_or_404(delivery_id)
    if form.validate_on_submit():
        new_status = form.status.data
        old_status = delivery.status

        if old_status == new_status:
            flash('Status is already up to date.')
            return redirect(url_for('delivery.mydeliveries'))

        delivery.status = new_status
        order = Order.query.filter(Order.order_id == delivery.order_id).first()
        order.status = form.status.data
        delivery.end_time = datetime.utcnow()
        if form.delivery_prove.data:
            image_filename = save_delivery_picture(form.delivery_prove.data)
            delivery.customer_pic = image_filename

        db.session.add(delivery)
        db.session.add(order)
        try:
            db.session.commit()
            flash(f" End time{delivery.end_time}, Start time{delivery.timestamp}")
            # 🔔 Message
            message = f"Delivery #{delivery.id} status changed from {old_status} to {new_status}"

            create_notification(user_type='customer', user_id=order.user_id, message=message)

            # 🔔 Notify pharmacy & emit event

            create_notification(user_type='pharmacy', user_id=order.pharmacy_id, message=message)

            flash('Delivery status successfully updated.')

        except IntegrityError:
            db.session.rollback()
            flash('An error occurred while updating the delivery. Please try again.')

        return redirect(url_for('delivery.mydeliveries'))

    flash("Form failed to validate.")
    return redirect(url_for('delivery.mydeliveries'))


@delivery.route('/deliverylayout', methods=["POST", "GET"])
def deliverylayout():
    formpharm = Set_PharmacyForm()
    pharmacies = Pharmacy.query.all()
    total_count = 0
    pharmacy = Pharmacy.query.get_or_404(session.get('pharmacy_id'))
    total_count = Order.query.filter(Order.pharmacy_id == session.get('pharmacy_id'), Order.status == "Ready").all().count()
    formpharm.pharmacy.choices = [(p.id, p.name) for p in pharmacies]
    return render_template('deliverylayout.html', formpharm=formpharm, total_count=total_count,
                           pharmacy=pharmacy)

@delivery.route('/set_pharmacy', methods=['POST', 'GET'])
def set_pharmacy():
    formpharm = Set_PharmacyForm()
    formpharm.pharmacy.choices=[(-1, "Select a Pharmacy")] + [(p.id, p.name) for p in Pharmacy.query.all()]
    if formpharm.validate_on_submit():
        session['pharmacy_id'] = formpharm.pharmacy.data
        return redirect(url_for('delivery.dashboard', pharmacy_id=formpharm.pharmacy.data))
    elif formpharm.errors:
        print(formpharm.errors)
        return formpharm.errors
    else:

application/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

application/pharmacy/__init__.py
from flask import Blueprint

pharmacy = Blueprint('pharmacy', __name__)

from . import views

application/templates/adminslayout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{{ current_user.name }} {% endblock %}</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/sb-admin-2.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/adminstyle.css') }}">
    <link href="{{url_for('static', filename='css/fontawesome-free/css/all.min.css')}}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='lib/bootstrap/dist/css/bootstrap.min.css')}}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/site.css')}}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/_Layout.css')}}"/>
</head>

<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
                <div class="sidebar-brand-icon rotate-n-15"></div>
                <div class="sidebar-brand-text mx-3">MediCart Admin Dashboard</div>
            </a>

            <!-- Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('pharmacy.adminpage') }}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <hr class="sidebar-divider">

            <!-- Pharmacy Management -->
            <div class="sidebar-heading">Pharmacy Management</div>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('admin.pending_verification') }}">
                    <i class="fas fa-spinner"></i>
                    <span>Pharmacies Pending Requests</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('admin.registered_pharmacies') }}">
                    <i class="fa fa-bars"></i>
                    <span>Registered Pharmacies</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('admin.register_pharmacy') }}">
                    <i class="fas fa-user-plus"></i>
                    <span>Manually Register Pharmacy</span>
                </a>
            </li>

            <hr class="sidebar-divider">
            <div class="sidebar-heading">Inventory Management</div>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('pharmacy.products') }}">
                    <i class="fas fa-th-list"></i>
                    <span>View All Products</span>
                </a>
            </li>

            <hr class="sidebar-divider">
            <div class="sidebar-heading">User Management</div>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('pharmacy.addstaff') }}">
                    <i class="fas fa-user-plus"></i>
                    <span>Add Admin User</span>
                </a>
            </li>

            <hr class="sidebar-divider d-none d-md-block">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.logout') }}">
                    <i class="fas fa-sign-out-alt"></i>
                    <span>Logout</span>
                </a>
            </li>
        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">
                <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                    <i class="fa fa-bars"></i>
                </button>

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>

                        <li class="nav-item dropdown no-arrow mx-1">
                            <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown">
                                <i class="fas fa-bell fa-fw"></i>
                                <span class="badge badge-danger badge-counter">{{ count }}</span>
                            </a>
                            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in">
                                <h6 class="dropdown-header">Notification Center</h6>
                                {% for note in unread_notifications %}
                                <a class="dropdown-item d-flex align-items-center" href="{{ url_for('pharmacy.mark_notification_read', notification_id=note.id) }}">
                                    <div class="mr-3">
                                        <div class="icon-circle bg-primary">
                                            <i class="fas fa-file-alt text-white"></i>
                                        </div>
                                    </div>
                                    <div>
                                        <div class="small text-gray-500">{{ note.timestamp.strftime('%Y-%m-%d %H:%M') }}</div>
                                        <span class="font-weight-bold">{{ note.message }}</span>
                                    </div>
                                </a>
                                {% endfor %}
                                <a class="dropdown-item text-center small text-gray-500" href="#">Show All Notifications</a>
                            </div>
                        </li>

                        <div class="topbar-divider d-none d-sm-block"></div>
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ current_user.name }}</span>
                                <img class="img-profile rounded-circle" src="{{ url_for('static', filename='css/images/undraw_profile.svg') }}">
                            </a>
                        </li>
                    </ul>
                </nav>

                <div class="row">
                    {% with messages = get_flashed_messages() %}
                    {% if messages %}
                    <div class="alert alert-success" role="alert">
                        {{ messages[0] }}
                    </div>
                    {% endif %}
                    {% endwith %}

                    {% block content %}{% endblock %}
                </div>
            </div>
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; MediCart 2025</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->
        </div>
    </div>

    <!-- Scroll to Top Button -->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Scripts -->
    <script src="{{ url_for('static', filename='vendor/jquery/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/jquery-easing/jquery.easing.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/sb-admin-2.min.js') }}"></script>


</body>
</html>